
// import 'dart:io'; // Removed for web compatibility
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:taasclub/features/game/game_room.dart';
import 'package:taasclub/features/ledger/ledger_service.dart';
import 'package:taasclub/features/ledger/settlement_service.dart';
import 'package:taasclub/features/ledger/transaction_model.dart';
import 'package:share_plus/share_plus.dart';
// import 'package:path_provider/path_provider.dart'; // Removed for web compatibility

final ledgerProvider = FutureProvider.family<GameRoom?, String>((ref, gameId) {
  final ledgerService = ref.watch(ledgerServiceProvider);
  return ledgerService.getGame(gameId);
});

class LedgerScreen extends ConsumerStatefulWidget {
  final String gameId;

  const LedgerScreen({super.key, required this.gameId});

  @override
  ConsumerState<LedgerScreen> createState() => _LedgerScreenState();
}

class _LedgerScreenState extends ConsumerState<LedgerScreen> {
  final GlobalKey _receiptKey = GlobalKey();
  bool _isGeneratingImage = false;

  /// Calculate settlements from game scores
  List<Transaction> _calculateSettlements(GameRoom game) {
    final settlementService = SettlementService();
    // Make a copy of scores to avoid mutating the original
    final scoresCopy = Map<String, int>.from(game.scores);
    return settlementService.calculateDebts(scoresCopy, game.config.pointValue);
  }

  /// Get player name from ID
  String _getPlayerName(GameRoom game, String playerId) {
    final player = game.players.firstWhere(
      (p) => p.id == playerId,
      orElse: () => Player(id: playerId, name: 'Unknown'),
    );
    return player.profile?.displayName ?? player.name;
  }

  /// Share settlement receipt as text
  void _shareAsText(GameRoom game, List<Transaction> transactions) {
    final buffer = StringBuffer();
    buffer.writeln('🎮 ClubRoyale Settlement Receipt');
    buffer.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buffer.writeln('📋 Game: ${game.name}');
    buffer.writeln('💰 Point Value: ${game.config.pointValue.toInt()} units');
    buffer.writeln('');
    buffer.writeln('📊 Final Scores:');
    for (final player in game.players) {
      final score = game.scores[player.id] ?? 0;
      final name = player.profile?.displayName ?? player.name;
      final icon = score > 0 ? '🟢' : (score < 0 ? '🔴' : '⚪');
      buffer.writeln('  $icon $name: $score pts');
    }
    buffer.writeln('');
    
    if (transactions.isEmpty) {
      buffer.writeln('✅ All settled! No payments needed.');
    } else {
      buffer.writeln('💸 Settlements:');
      for (final tx in transactions) {
        final from = _getPlayerName(game, tx.fromPlayer);
        final to = _getPlayerName(game, tx.toPlayer);
        buffer.writeln('  → $from pays $to: ${tx.amount.toInt()} units');
      }
    }
    buffer.writeln('');
    buffer.writeln('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    buffer.writeln('Generated by ClubRoyale');

    Share.share(buffer.toString(), subject: 'Settlement: ${game.name}');
  }

  /// Generate and share receipt as image
  Future<void> _shareAsImage(GameRoom game) async {
    if (kIsWeb) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Image sharing not supported on web yet')),
      );
      return;
    }

    setState(() => _isGeneratingImage = true);

    try {
      /* 
      // TODO: Restore mobile implementation with conditional import to fix build
      
      // Wait for the widget to be rendered
      await Future.delayed(const Duration(milliseconds: 100));

      final boundary = _receiptKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) {
        throw Exception('Could not capture receipt');
      }

      final image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      final bytes = byteData!.buffer.asUint8List();

      // Save to temp file
      // final tempDir = await getTemporaryDirectory();
      // final fileName = 'settlement_${game.id ?? 'receipt'}_${DateTime.now().millisecondsSinceEpoch}.png';
      // final file = File('${tempDir.path}/$fileName');
      // await file.writeAsBytes(bytes);

      // Share the image
      // await Share.shareXFiles(
      //   [XFile(file.path)],
      //   text: 'Settlement Receipt for ${game.name}',
      //   subject: 'ClubRoyale Settlement',
      // );
      */
      
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Image generation temporarily disabled for web build')),
      );

    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to generate image: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isGeneratingImage = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final ledgerAsyncValue = ref.watch(ledgerProvider(widget.gameId));
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Settlement'),
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.go('/'),
        ),
        actions: [
          // Share menu
          PopupMenuButton<String>(
            icon: const Icon(Icons.share),
            onSelected: (value) {
              ledgerAsyncValue.whenData((game) {
                if (game == null) return;
                final transactions = _calculateSettlements(game);
                if (value == 'text') {
                  _shareAsText(game, transactions);
                } else if (value == 'image') {
                  _shareAsImage(game);
                }
              });
            },
            itemBuilder: (context) => [
              const PopupMenuItem(
                value: 'text',
                child: ListTile(
                  leading: Icon(Icons.text_fields),
                  title: Text('Share as Text'),
                  contentPadding: EdgeInsets.zero,
                ),
              ),
              const PopupMenuItem(
                value: 'image',
                child: ListTile(
                  leading: Icon(Icons.image),
                  title: Text('Share as Image'),
                  contentPadding: EdgeInsets.zero,
                ),
              ),
            ],
          ),
        ],
      ),
      body: ledgerAsyncValue.when(
        data: (game) {
          if (game == null) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.error_outline, size: 64, color: colorScheme.error),
                  const SizedBox(height: 16),
                  const Text('Game not found'),
                  const SizedBox(height: 16),
                  FilledButton(
                    onPressed: () => context.go('/'),
                    child: const Text('Back to Lobby'),
                  ),
                ],
              ),
            );
          }

          final transactions = _calculateSettlements(game);
          
          // Sort players by score (highest first)
          final sortedPlayers = List<Player>.from(game.players)
            ..sort((a, b) => (game.scores[b.id] ?? 0).compareTo(game.scores[a.id] ?? 0));

          return SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Receipt Card (capturable for image)
                  RepaintBoundary(
                    key: _receiptKey,
                    child: Container(
                      decoration: BoxDecoration(
                        color: colorScheme.surface,
                        borderRadius: BorderRadius.circular(16),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.1),
                            blurRadius: 10,
                            offset: const Offset(0, 4),
                          ),
                        ],
                      ),
                      child: Column(
                        children: [
                          // Header
                          Container(
                            padding: const EdgeInsets.all(20),
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                colors: [colorScheme.primary, colorScheme.secondary],
                                begin: Alignment.topLeft,
                                end: Alignment.bottomRight,
                              ),
                              borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
                            ),
                            child: Column(
                              children: [
                                const Icon(Icons.receipt_long, size: 48, color: Colors.white),
                                const SizedBox(height: 8),
                                Text(
                                  'Settlement Receipt',
                                  style: theme.textTheme.titleLarge?.copyWith(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                Text(
                                  game.name,
                                  style: theme.textTheme.bodyMedium?.copyWith(
                                    color: Colors.white.withOpacity(0.8),
                                  ),
                                ),
                              ],
                            ),
                          ),

                          // Game Info
                          Padding(
                            padding: const EdgeInsets.all(16),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceAround,
                              children: [
                                _InfoChip(
                                  icon: Icons.people,
                                  label: '${game.players.length} Players',
                                ),
                                _InfoChip(
                                  icon: Icons.monetization_on,
                                  label: '${game.config.pointValue.toInt()} units/pt',
                                ),
                                _InfoChip(
                                  icon: Icons.repeat,
                                  label: '${game.config.totalRounds} Rounds',
                                ),
                              ],
                            ),
                          ),

                          const Divider(height: 1),

                          // Scores Section
                          Padding(
                            padding: const EdgeInsets.all(16),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Final Scores',
                                  style: theme.textTheme.titleMedium?.copyWith(
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                const SizedBox(height: 12),
                                ...sortedPlayers.map((player) {
                                  final score = game.scores[player.id] ?? 0;
                                  final isWinner = score > 0;
                                  final isLoser = score < 0;
                                  final moneyValue = (score * game.config.pointValue).abs();
                                  
                                  return Padding(
                                    padding: const EdgeInsets.symmetric(vertical: 4),
                                    child: Row(
                                      children: [
                                        CircleAvatar(
                                          radius: 16,
                                          backgroundColor: isWinner 
                                              ? Colors.green.withOpacity(0.2)
                                              : isLoser 
                                                  ? Colors.red.withOpacity(0.2)
                                                  : colorScheme.surfaceContainerHighest,
                                          child: Text(
                                            player.name[0].toUpperCase(),
                                            style: TextStyle(
                                              color: isWinner ? Colors.green : isLoser ? Colors.red : null,
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ),
                                        const SizedBox(width: 12),
                                        Expanded(
                                          child: Text(
                                            player.profile?.displayName ?? player.name,
                                            style: theme.textTheme.bodyLarge,
                                          ),
                                        ),
                                        Column(
                                          crossAxisAlignment: CrossAxisAlignment.end,
                                          children: [
                                            Text(
                                              '$score pts',
                                              style: theme.textTheme.titleMedium?.copyWith(
                                                color: isWinner ? Colors.green : isLoser ? Colors.red : null,
                                                fontWeight: FontWeight.bold,
                                              ),
                                            ),
                                            Text(
                                              '${isWinner ? '+' : isLoser ? '-' : ''}${moneyValue.toInt()} units',
                                              style: theme.textTheme.bodySmall?.copyWith(
                                                color: colorScheme.onSurfaceVariant,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ],
                                    ),
                                  );
                                }),
                              ],
                            ),
                          ),

                          const Divider(height: 1),

                          // Settlements Section
                          Padding(
                            padding: const EdgeInsets.all(16),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  children: [
                                    const Icon(Icons.swap_horiz, size: 20),
                                    const SizedBox(width: 8),
                                    Text(
                                      'Settlements',
                                      style: theme.textTheme.titleMedium?.copyWith(
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 12),
                                if (transactions.isEmpty)
                                  Container(
                                    padding: const EdgeInsets.all(16),
                                    decoration: BoxDecoration(
                                      color: Colors.green.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    child: const Row(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        Icon(Icons.check_circle, color: Colors.green),
                                        SizedBox(width: 8),
                                        Text('All settled! No payments needed.'),
                                      ],
                                    ),
                                  )
                                else
                                  ...transactions.map((tx) => _TransactionTile(
                                    fromName: _getPlayerName(game, tx.fromPlayer),
                                    toName: _getPlayerName(game, tx.toPlayer),
                                    amount: tx.amount,
                                  )),
                              ],
                            ),
                          ),

                          // Footer
                          Container(
                              padding: const EdgeInsets.all(12),
                              decoration: BoxDecoration(
                              color: colorScheme.surfaceContainerHighest,
                              borderRadius: const BorderRadius.vertical(bottom: Radius.circular(16)),
                              ),
                              child: Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                  Icon(Icons.sports_esports, size: 16, color: colorScheme.onSurfaceVariant),
                                  const SizedBox(width: 8),
                                  Text(
                                  'Generated by ClubRoyale',
                                  style: theme.textTheme.bodySmall?.copyWith(
                                      color: colorScheme.onSurfaceVariant,
                                  ),
                                  ),
                              ],
                              ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const SizedBox(height: 24),

                  // Action Buttons
                  Row(
                    children: [
                      Expanded(
                        child: OutlinedButton.icon(
                          onPressed: () {
                            final transactions = _calculateSettlements(game);
                            _shareAsText(game, transactions);
                          },
                          icon: const Icon(Icons.text_fields),
                          label: const Text('Share Text'),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: FilledButton.icon(
                          onPressed: _isGeneratingImage ? null : () => _shareAsImage(game),
                          icon: _isGeneratingImage 
                              ? const SizedBox(
                                  width: 18,
                                  height: 18,
                                  child: CircularProgressIndicator(strokeWidth: 2),
                                )
                              : const Icon(Icons.photo_camera),
                          label: Text(_isGeneratingImage ? 'Generating...' : 'Share Image'),
                        ),
                      ),
                    ],
                  ),

                  const SizedBox(height: 16),

                  // Back to Lobby
                  TextButton(
                    onPressed: () => context.go('/'),
                    child: const Text('Back to Lobby'),
                  ),
                ],
              ),
            ),
          );
        },
        loading: () => const Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CircularProgressIndicator(),
              SizedBox(height: 16),
              Text('Loading settlement...'),
            ],
          ),
        ),
        error: (error, stack) => Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.error_outline, size: 64, color: colorScheme.error),
              const SizedBox(height: 16),
              Text('Error: $error'),
            ],
          ),
        ),
      ),
    );
  }
}

class _InfoChip extends StatelessWidget {
  final IconData icon;
  final String label;

  const _InfoChip({required this.icon, required this.label});

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(icon, size: 16, color: Theme.of(context).colorScheme.onSurfaceVariant),
        const SizedBox(width: 4),
        Text(label, style: Theme.of(context).textTheme.bodySmall),
      ],
    );
  }
}

class _TransactionTile extends StatelessWidget {
  final String fromName;
  final String toName;
  final double amount;

  const _TransactionTile({
    required this.fromName,
    required this.toName,
    required this.amount,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: colorScheme.primaryContainer.withOpacity(0.3),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: colorScheme.outline.withOpacity(0.2)),
      ),
      child: Row(
        children: [
          // From avatar
          CircleAvatar(
            radius: 16,
            backgroundColor: Colors.red.withOpacity(0.2),
            child: Text(
              fromName[0].toUpperCase(),
              style: const TextStyle(color: Colors.red, fontWeight: FontWeight.bold, fontSize: 12),
            ),
          ),
          const SizedBox(width: 8),
          // From name
          Expanded(
            child: Text(fromName, style: theme.textTheme.bodyMedium),
          ),
          // Arrow with amount
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
            decoration: BoxDecoration(
              color: colorScheme.surface,
              borderRadius: BorderRadius.circular(16),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  '${amount.toInt()}',
                  style: theme.textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: colorScheme.primary,
                  ),
                ),
                const SizedBox(width: 4),
                Icon(Icons.arrow_forward, size: 16, color: colorScheme.primary),
              ],
            ),
          ),
          const SizedBox(width: 8),
          // To name
          Expanded(
            child: Text(toName, style: theme.textTheme.bodyMedium, textAlign: TextAlign.right),
          ),
          const SizedBox(width: 8),
          // To avatar
          CircleAvatar(
            radius: 16,
            backgroundColor: Colors.green.withOpacity(0.2),
            child: Text(
              toName[0].toUpperCase(),
              style: const TextStyle(color: Colors.green, fontWeight: FontWeight.bold, fontSize: 12),
            ),
          ),
        ],
      ),
    );
  }
}
